Adding ANGLE: Changes via conversation in issue #1317
dotnet/Silk.NET pull request #1321
Opened 2023-03-06 04:46 UTC by cyraid

# Summary of the PR
+ Add Bool Enum (for GLFW_TRUE/GLFW_FALSE)
+ Add AnglePlatformType Enum for InitHint (added in GLFW 3.4)
+ Change InitHint to use int, as the official glfw library.

# Related issues, Discord discussions, or proposals
Issue #1317 

# Further Comments
Thanks guys.

2023-03-06 04:47 UTC, cyraid commented
> 

@dotnet-policy-service agree

2023-03-06 06:02 UTC, Perksey commented
WAIT THAT’S WORKING NOW?!?! FINALLY THE BOT HAS COME TO LIFE 🤦‍♂️

2023-03-09 00:52 UTC, Beyley requested changes

2023-03-09 00:52 UTC, Beyley commented on src/Windowing/Silk.NET.GLFW/Glfw.cs
> +        public partial void InitHint(InitHint hint, int value);
We are trying to avoid breaking changes in the 2.x series, can you make this an overload instead?

2023-03-11 20:14 UTC, Perksey approved these changes

2023-03-12 10:35 UTC, Beyley approved these changes

2023-03-12 16:57 UTC, merged