Add shaderc bindings
dotnet/Silk.NET pull request #1490
Opened 2023-06-06 06:42 UTC by Beyley

# Summary of the PR
Adds Shaderc bindings

# Related issues, Discord discussions, or proposals
Closes #482

2023-06-12 17:42 UTC, Perksey reviewed
Bindings portion is approved

2023-06-17 23:11 UTC, hYdos approved these changes
this looks good. whats it waiting on?

2023-06-17 23:15 UTC, Beyley commented
> this looks good. whats it waiting on?

Native libraries, i have the Zig build script to do this, i just need to hook it up to our CI, and i have not found the time/energy to do so yet
[build.zig.txt](https://github.com/dotnet/Silk.NET/files/11780199/build.zig.txt)

2023-06-23 22:25 UTC, Beyley commented on build/nuke/Native/SDL2.cs
> +                    CopyFile(x86BuildDir / "lib" / "libSDL2-2.0.so.0.2600.5", runtimes / "linux-x86" / "native" / "libSDL2-2.0.so", FileExistsPolicy.Overwrite);
it has been made Globby

2023-06-23 22:31 UTC, Perksey requested changes

2023-06-23 22:31 UTC, Perksey commented on build/nuke/Native/SDL2.cs
> +                    CopyFile(ARM64BuildDir / "libSDL2-2.0.so.0.2600.5", runtimes / "linux-arm64" / "native" / "libSDL2-2.0.so", FileExistsPolicy.Overwrite);
Tlobby here too

2023-06-23 22:38 UTC, Perksey approved these changes
Dtunbjeb approval

2023-06-24 08:53 UTC, Beyley commented
Due to broken CLA check, merging manually

2023-06-24 08:53 UTC, merged