Add OpenCL Demo
dotnet/Silk.NET pull request #1721
Opened 2023-10-12 13:22 UTC by LonerDo

2023-10-12 13:27 UTC, LonerDo commented
@dotnet-policy-service agree

2023-10-12 16:34 UTC, Perksey requested changes
This looks really good, thank you so much for your amazing contribution! Just a few minor nits, most of this I couldn't do better if I tried!

2023-10-12 16:34 UTC, Perksey commented on examples/CSharp/OpenCL Tutorials/HelloWorld/HelloWorld.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Can you move this project to the `OpenCL Demos` folder until we figure out what a formal set of tutorials looks liek for OpenCL?

2023-10-12 16:34 UTC, Perksey commented on examples/CSharp/OpenCL Tutorials/HelloWorld/Program.cs
> +                Console.WriteLine($"文件不存在:{fileName}");
```suggestion
                Console.WriteLine($"File does not exist: {fileName}");
```

2023-10-12 16:34 UTC, Perksey commented on examples/CSharp/OpenCL Tutorials/HelloWorld/Program.cs
> +        static unsafe nint CreatContext(CL cL)
```suggestion
        static unsafe nint CreateContext(CL cL)
```
(and rename usages)

2023-10-13 18:31 UTC, Perksey approved these changes
Awesome, thank you so much for your contribution!

2023-10-14 05:25 UTC, merged