Regenerate bindings
dotnet/Silk.NET pull request #1851
Opened 2023-12-19 03:12 UTC by Beyley

# Summary of the PR
i had nothing else to do so i figured i should probably do this

2023-12-21 18:48 UTC, Beyley commented
All thats left is updating shaderc, then this will be ready to review

Swiftshader has been broken for awhile, and so has vkd3d, i need to revive #1678 at some point
I'll leave those both broken, and fix it at somepoint else

2023-12-22 00:09 UTC, Perksey approved these changes
#1851 Is A Perfectly Balanced PR With No Exploits

2023-12-22 00:09 UTC, Perksey commented on src/SPIRV/Silk.NET.SPIRV.Reflect/Enums/AnonymousEnumSpirvReflectL281C1.gen.cs
> +    public enum AnonymousEnumSpirvReflectL281C1 : int
Is it possible to give this a slightly more sensible name? No idea what, but something that doesn't change every header update would be nice.

2023-12-22 00:10 UTC, Perksey requested changes
LOL I forgot I wrote a comment

2023-12-22 04:51 UTC, Perksey approved these changes

2023-12-22 04:51 UTC, Perksey commented
CLA has derped, fast approving.

2023-12-22 04:51 UTC, merged