Rewritten proposal for Windowing 3.0
dotnet/Silk.NET pull request #2353
Opened 2024-11-12 13:35 UTC by Perksey

# Summary of the PR
What the title says, other words are in the proposal.

# Related issues, Discord discussions, or proposals
Too many Discord conversations to coalesce over the years, feel free to ask if you would like specifics.

# Further Comments
All in the proposal.

2024-11-14 01:48 UTC, curin requested changes

2024-11-14 01:48 UTC, curin commented on documentation/proposals/Proposal - Windowing 3.0.md
> +Silk.NET 3.0 aims to support Windows, Linux (X/11 and Wayland), macOS, iOS, and macOS. The goal of this proposal is to
```suggestion
Silk.NET 3.0 aims to support Windows, Linux (X/11 and Wayland), macOS, iOS, and Android. The goal of this proposal is to
```

2024-11-14 14:30 UTC, Perksey commented on documentation/proposals/Proposal - Windowing 3.0.md
> +Silk.NET 3.0 aims to support Windows, Linux (X/11 and Wayland), macOS, iOS, and macOS. The goal of this proposal is to
lol thanks.

2024-11-14 16:39 UTC, curin requested changes

2024-11-14 16:39 UTC, curin commented on documentation/proposals/Proposal - Windowing 3.0.md
> +# The Vulkan Component
We have a component for Vulkan and OpenGL, but what about DirectX?

2024-11-14 17:06 UTC, curin commented on documentation/proposals/Proposal - Windowing 3.0.md
> +# The Vulkan Component
👍

2024-11-14 17:06 UTC, curin approved these changes

2025-01-22 16:50 UTC, Perksey commented
@curin just realised you might not have had a pre-review of the pointer device proposal looking at the commit history

2025-01-22 17:13 UTC, curin commented
glanced through and it looks fine to me

2025-01-26 20:21 UTC, Perksey commented
# Windowing
- Approved, with changes...
- `Name` for colloquial names should be `Description` to clarify it's a non-programmatic user-facing description

2025-01-26 20:55 UTC, Perksey commented
# Input

- Approved, with changes...
- `IPointer` should be renamed to `IPointerDevice` 
- `CursorFlags` remove - unused

2025-01-27 09:20 UTC, merged