[WIP] Enhanced Input Events
dotnet/Silk.NET pull request #402
Opened 2021-01-12 15:56 UTC by ThomasMiz

# Summary of the PR
Adds missing input functionality, as discussed in Discord and in issue #399

2021-03-05 20:11 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    event Action<MouseMoveEventArgs> MouseMove;
make separate, new event for this new-style stuff

2021-03-05 20:11 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    event Action<MouseMoveEventArgs> MouseMove;
Need to come up with a new name for the new-style move struct.

2021-03-05 20:11 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    event Action<MouseButtonEventArgs> DoubleClick;
Merge into a new one

2021-03-05 20:11 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    event Action<MouseButtonEventArgs> MouseUp;
Merge into new

2021-03-05 20:11 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    event Action<KeyEventArgs> KeyUp;
Merge into one single new event

2021-03-05 20:11 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    event Action<CharacterTypedEventArgs> CharacterTyped;
Rename back to KeyChar, break seems fine I think.

2021-03-05 20:11 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    event Action<MouseScrollEventArgs> Scroll;
Break seems fine I think.

2021-04-10 19:09 UTC, Perksey commented
Are there plans to update this proposal according to feedback?

2021-05-01 18:19 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/Silk.NET?pullRequest=402) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/Silk.NET?pullRequest=402) before we can accept your contribution.<br/><br/>:x: ThomasMiz [sign now](https://cla.dotnetfoundation.org/dotnet/Silk.NET?pullRequest=402)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/Silk.NET?pullRequest=402) it.</sub>

2021-07-03 18:58 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    event Action<MouseButtonEventArgs> DoubleClick;
I don't know why I said this as I don't want to in retrospect.

2021-07-03 18:59 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    event Action<MouseMoveEventArgs> MouseMove;
`MouseMoveEvent` is sufficient in retrospect.

2021-07-03 18:59 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    event Action<MouseButtonEventArgs> MouseUp;
Actually I don't think there's a need.

2021-07-03 18:59 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    event Action<KeyEventArgs> KeyUp;
Same again.

2021-07-03 19:03 UTC, Perksey requested changes
Just one last comment remaining for the preliminary review (before we take this to the working group again) about adding constructors to the API, but generally I like this pattern of "event being an action, event parameters being a struct" i.e. "user has pressed a button down, here's a struct containing which button". I don't think one event should reflect multiple logical actions so I've discarded my comments suggesting this.

Feel free to change up the proposal as well if after a nearly half a year you've got some new ideas. I've retargeted the PR to use the 3.0 proposals branch.

2021-07-17 13:24 UTC, Perksey requested changes
One final pass, very simple changes just click the buttons :P

2021-07-17 13:24 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    NumLock = 1 << 6
We're not using the rightmost bit!

```suggestion
    Shift = 1 << 0,
    Control = 1 << 1,
    Alt = 1 << 2,
    Super = 1 << 3,
    CapsLock = 1 << 4,
    NumLock = 1 << 5
```

2021-07-17 13:24 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    public KeyDownEvent(IKeyboard keyboard, Key key, int keyCode, KeyModifiers modifiers, bool isRepeat)
```suggestion
    public KeyDownEvent(IKeyboard keyboard, Key key, int keyCode, KeyModifiers modifiers, bool isRepeat);
```

2021-07-17 13:24 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    public KeyUpEvent(IKeyboard keyboard, Key key, int keyCode, KeyModifiers modifiers)
```suggestion
    public KeyUpEvent(IKeyboard keyboard, Key key, int keyCode, KeyModifiers modifiers);
```

2021-07-17 13:24 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    public KeyCharEvent(IKeyboard keyboard, char character, int keyCode)
```suggestion
    public KeyCharEvent(IKeyboard keyboard, char character, int keyCode);
```

2021-07-17 13:24 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    public MouseMoveEvent(IMouse mouse, Vector2 position, Vector2 delta)
```suggestion
    public MouseMoveEvent(IMouse mouse, Vector2 position, Vector2 delta);
```

2021-07-17 13:24 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    public MouseButtonEvent(IMouse mouse, Vector2 position, MouseButton button, KeyModifiers modifiers)
```suggestion
    public MouseButtonEvent(IMouse mouse, Vector2 position, MouseButton button, KeyModifiers modifiers);
```

2021-07-17 13:24 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +    public MouseScrollEvent(IMouse mouse, Vector2 position, Vector2 wheelPosition, Vector2 delta)
```suggestion
    public MouseScrollEvent(IMouse mouse, Vector2 position, Vector2 wheelPosition, Vector2 delta);
```

2021-07-17 13:24 UTC, Perksey commented on documentation/proposals/Proposal - Enhanced Input Events.md
> +This would replace the current ScrollWheel struct.
I doubt it, as we'll need to expose the scroll wheel as a property on `IMouse` as well (i.e. outside of the event)

```suggestion
```

2021-07-17 13:38 UTC, Perksey approved these changes

2021-07-17 13:39 UTC, merged