apply deadzone to sdl gamepad
dotnet/Silk.NET pull request #451
Opened 2021-04-08 02:06 UTC by KyleGalvin

# Summary of the PR

## Purpose
Support the deadzone feature in Silk.NET.Input.Sdl
Specifically, application of the Deadzone object to SdlGamepad

## Background
SdlGamepad has a Deadzone object, however the deadzone is not applied in SdlGamepad DoEvent method.
This prevents the SdlGamepad DoEvent method from filtering out superfluous ThumbstickMoved events on idle.
This may also cause unwanted thumbstick drift.

## Considerations
**This fix is untested!**
Due to environmental factors and my general unfamiliarity with the project dependency tree, I was unable to run this fix to verify its suitability. It does, however, compile.

## Assumptions made
1) I have made the assumption the SdlGamepad._thumbsticks array is not modified elsewhere, since it is private. This means that it should now always hold a value with the deadzone applied.

2) I have assumed the ThumbstickMoved event is driven directly off the _thumbsticksChanged bool array, and that it is correct to compare the previous state (with deadzone applied) to the current state (with deadzone applied) and only trigger the Thumbstick moved event if they are not equal.

2021-04-08 02:06 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/Silk.NET?pullRequest=451) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/Silk.NET?pullRequest=451) before we can accept your contribution.<br/><br/>:x: KyleGalvin [sign now](https://cla.dotnetfoundation.org/dotnet/Silk.NET?pullRequest=451)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/Silk.NET?pullRequest=451) it.</sub>

2021-04-09 02:54 UTC, KyleGalvin commented
This PR has been personally tested and validated after a discussion with @Perksey on discord about how to best test code.
A related PR contains a tutorial that may be desirable that was derived from my test scenario.
https://github.com/dotnet/Silk.NET/pull/452

For my testing scenarios, I was sure to create a wide deadzone (0.5f), and force the sdl input driver with SdlWindowing.Use()
Stepping through the code, I verified the input type came up as Sdl.

2021-04-10 13:00 UTC, Perksey requested changes

2021-04-10 19:17 UTC, Perksey approved these changes

2021-04-10 19:39 UTC, merged