added input tutorial
dotnet/Silk.NET pull request #452
Opened 2021-04-09 02:51 UTC by KyleGalvin

# Summary of the PR
Add a tutorial for gamepad inputs

# Related issues, Discord discussions, or proposals
This PR came out of wanting to test my previous PR here:
https://github.com/dotnet/Silk.NET/pull/451

# Further Comments
This did help me validate my previous PR as functional.
I did, however, find two more bugs since. I'll be following up on those.

2021-04-09 02:58 UTC, KyleGalvin commented on src/Windowing/Silk.NET.Windowing.Common/Silk.NET.Windowing.Common.csproj
> +        <TargetFrameworks>netstandard2.0;netstandard2.1;netcoreapp3.1</TargetFrameworks>
Since this is the tutorial target framework, I needed to add this or I would get 'not found' at runtime.

2021-04-09 02:59 UTC, KyleGalvin commented on examples/CSharp/Tutorial 1.6 - Hello Gamepad/Program.cs
> +            //if a controller is plugged in before the application is launched, ConnectionChanged may or may not fire depending on the underlying driver used.
This behavior is inconsistent between glfw and sdl. Registering gamepads OnLoad and on ConnectionChanged seems to capture both scenarios well enough for a basic tutorial

2021-04-09 03:00 UTC, KyleGalvin commented on examples/CSharp/Tutorial 1.6 - Hello Gamepad/Program.cs
> +            RegisterGamepads();
If a controller is disconnected, arg1 is false. If the last controller available is disconnected, SDL throws a hard exception.

This is something I hope to follow up on next.

2021-04-09 03:03 UTC, KyleGalvin commented on examples/CSharp/Tutorial 1.6 - Hello Gamepad/Program.cs
> +            Console.WriteLine($"gamepad {arg1.Index} joystick {arg2.Index} moved to position {arg2.X},{arg2.Y}.");
This console output and the occasional break point in these event handlers are what I found helpful enough to propose this as a tutorial.

2021-04-09 03:04 UTC, KyleGalvin commented on Silk.NET.sln
> +		{BD86AB4D-74FD-429D-9AEE-79B0C429BB3A}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
Go home, visual studio. You're drunk.

2021-06-01 17:04 UTC, Perksey requested changes
Sorry for the delay, given the latest changes to how the examples folder is structured I can now review this.

This is an amazing start and will do a good job in demonstrating our input library! Given this doesn't really fit into the main OpenGL tutorial series, I'd like this converted into a "demo" rather than a strict tutorial (literally just means putting it in a different folder). There's just a few other things too...

2021-06-01 17:04 UTC, Perksey commented on examples/CSharp/Tutorial 1.6 - Hello Gamepad/Tutorial 1.6 - Hello Gamepad.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Can you:
- merge in the latest `main`
- move this project to `examples/CSharp/HLU Demos/Gamepad Input Demo`

2021-06-01 17:04 UTC, Perksey commented on Silk.NET.sln
> +		{BD86AB4D-74FD-429D-9AEE-79B0C429BB3A}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
Seems fine.

2021-08-09 16:17 UTC, Perksey commented
Closing due to inactivity

2021-08-09 16:17 UTC, closed without merging