Fix `NU5127`, `NU5128`, and `NU1701` in relation to native packages.
dotnet/Silk.NET pull request #515
Opened 2021-06-09 12:23 UTC by alexrp

Fixes #514.

This resolves `NU5127` and `NU5128` at pack time. Also verified using a local package source that `NU1701` no longer occurs when consuming the package.

New versions of all the native packages should probably be pushed after this is merged.

2021-06-09 12:59 UTC, Perksey commented
Is this really enough to fix it?

2021-06-09 13:03 UTC, Perksey requested changes
Actually this makes sense, ok can you up the patch version (w in x.y.z.w) for each of the native packages? Happy to approve once this is done and will be included in the 2.6 July 2021 Update.

2021-06-09 13:41 UTC, alexrp commented
Done.

2021-06-10 11:59 UTC, Perksey approved these changes

2021-06-10 12:19 UTC, merged