"Winapi" support on NS20 and .NET 5
dotnet/Silk.NET pull request #561
Opened 2021-08-06 21:50 UTC by Perksey

2.7 is due today.

This implements support for platform-default P/Invoke calling conventions instead of blindly using Cdecl (which is incorrect!) This is something that was pointed out when SilkTouch development first started, but was not implemented.

On .NET Standard 2.0, seeing as there's no true way to specify "platform default" we use a "best effort" implementation to cover known cases. Right now, this is just 32-bit Windows being not Cdecl - there are no other concerns we know of today.

Codegen:
- [Assimp.WinapiNET5.gen.txt](https://github.com/dotnet/Silk.NET/files/6948095/Assimp.WinapiNET5.gen.txt)
- [Assimp.WinapiNS20.gen.txt](https://github.com/dotnet/Silk.NET/files/6948096/Assimp.WinapiNS20.gen.txt)

2021-08-06 21:53 UTC, HurricanKai requested changes
SilkTouch is run once per target.
Instead of delegating this to a runtime check that checks the Silk.NET.Core framework we built against, just put the #IF NET5_0 .... #else ... #endif right in the generated code (well not actually, just check in SilkTouch what target we are building).
Also, instead of having Winapi be the new default, just set it to be the default only for Assimp, that way we only have to multi-target Assimp to NET5 and NS.

2021-08-06 21:59 UTC, Perksey commented
> Instead of delegating this to a runtime check that checks the Silk.NET.Core framework we built against, just put the #IF NET5_0 .... #else ... #endif right in the generated code.

This uglies the code, both generated and generator and has zero gain. Not reworking just for this.

> Also, instead of having Winapi be the new default, just set it to be the default only for Assimp, that way we only have to multi-target Assimp to NET5 and NS.

This is a deviation from DllImport behaviour and expected behaviour, but fine.

2021-08-06 22:01 UTC, HurricanKai commented
> This uglies the code, both generated and generator and has zero gain. Not reworking just for this.
No it doesn't. It means there is zero code diff on .NET 5, and an extra if check on other platforms.

2021-08-06 22:01 UTC, Perksey commented
> No it doesn't. It means there is zero code diff on .NET 5, and an extra if check on other platforms.

There already is zero generated code diff on .NET 5.

2021-08-06 22:03 UTC, Perksey commented
Unless you mean diff between the outputs of the two different targets, in which case I'm not reworking this for that as it's absolutely zero gain.

2021-08-07 14:25 UTC, Perksey commented
Is there anything left to do here?

2021-08-07 22:49 UTC, HurricanKai approved these changes
Not very happy with this, but I'll merge it for 2.7

2021-08-07 22:49 UTC, merged

2021-08-07 22:53 UTC, Perksey commented
For the record doing your ifdef in the generated code tactic has no real positives and quite a few negatives for example at this scale it will decrease performance doing this check at reparse time rather than generation time in addition to all of my reasons outlined above. You would be going out of your way to increase the compiler's load purely because you want the output to be the same between the target frameworks, which it effectively isn't anyway given disabled preprocessor branches are just text which the compiler discards - so really it's just a courtesy for... I have no idea who?