Feature/vulkan struct chaining/approved
dotnet/Silk.NET pull request #706
Opened 2021-11-30 08:55 UTC by thargy

# Summary of the PR
Full implementation of Vulkan Struct chaining Proposals 1, 2 and 3.

# Related issues, Discord discussions, or proposals
* [Proposals Pull Request](https://github.com/dotnet/Silk.NET/pull/676)
* [Proposal 1](https://github.com/dotnet/Silk.NET/blob/4af9ffd769f8ba65e3c514149e2d7561c2ba1192/documentation/proposals/Proposal%20-%20Vulkan%20Struct%20Chaining%20-%20%231%20StructureType%20correction.md)
* [Proposal 2](https://github.com/dotnet/Silk.NET/blob/4af9ffd769f8ba65e3c514149e2d7561c2ba1192/documentation/proposals/Proposal%20-%20Vulkan%20Struct%20Chaining%20-%20%232%20Unmanaged%20Chaining.md)
* [Proposal 3]
(https://github.com/dotnet/Silk.NET/blob/4af9ffd769f8ba65e3c514149e2d7561c2ba1192/documentation/proposals/Proposal%20-%20Vulkan%20Struct%20Chaining%20-%20%233%20Managed%20Chaining.md)
* [Proposal 4](https://github.com/dotnet/Silk.NET/blob/4af9ffd769f8ba65e3c514149e2d7561c2ba1192/documentation/proposals/Proposal%20-%20Vulkan%20Struct%20Chaining%20-%20%234%20Chaining%20Metadata%20extensions.md)

# Further Comments
This is currently functionally complete.

Lead Reviewer: @Perksey

2021-11-30 09:00 UTC, thargy commented
# Working Group Discussion Summary
COPIED OVER FROM https://github.com/dotnet/Silk.NET/pull/676#issuecomment-982050756

All proposals provisionally approved, there are no significant comments and this won't need to come back to a meeting if these are addressed. Discussed in Working Group Meeting 29/11/2021.

## StructureType correction
* Must be explicit, must be implemented in a specific way.
  
  * Invisible to users
* Get-only property implies it's _just_ getting, so it makes sense being a method.
* There's a concern if we decided to make everything readonly in the future.
  
  * Could probably use withers when we get to that place.

**Consensus**

* Yes.

No discussion points, seems fine.

## Unmanaged Chaining
* **OPEN QUESTION:** OpenXR implications/applications?
  
  * copy pasting is fine.
* **OPEN QUESTION:** Should TChain be constrained to IChainStart?
  
  * doesn't really matter, but good to check anyways.
* "Chain interfaces (Optional)" no use case that we can think of, leave out [for now]. Can revisit if needs be.

**Consensus**

* Happy.

## Managed Chaining
* Assuming `ManagedCache` refers to `ManagedChain` (this should be fixed before merge)
* Ignoring actual implementation scrutiny for the purposes of proposal review
* This would be the recommended strategy for chaining/the mainstay.
  
  * unmanaged chain is specialized usage/"only if you know what you're doing"
* Should the base class be able to modify the chain?
* **OPEN QUESTION: ** Look at base append/truncate/duplicate. Not proposal critical, but would be nice to have.
* Could possibly implement IList instead of IReadOnlyList (well, both...)
* Append reminds us of StringBuilder/string things.

**Consensus**

* Happy
* Rename Append methods to Add
* More optional comments, see above.

## Metadata extensions.
* Shouldn't use reflection in game engine libraries (could be a gotcha)
* Pick n' mix of simple metadata additions which we can optionally add
* Sort of already covered by other proposals
* Proposal is basically "we already have this data, how do we/shall we expose this"
* Could be an extension package?
* Seems like the use cases are niche, unrealised, or otherwise not applicable or of concern to Silk.NET itself

**Consensus**

* Revisit in the future if we have a use case
* Merge as a "(Proposed) Proposal - " file and add a champion issue

2021-12-01 19:38 UTC, Perksey requested changes
Generated code looks fine, just a few nitpicks here and there (mostly on style, but some carried over from the original repo)

2021-12-01 19:38 UTC, Perksey commented on src/Core/Silk.NET.BuildTools/Bind/StructWriter.cs
> +                                break;
```suggestion
                            case "$VKSTRUCTUREDTYPE":
                            {
                                structuredType = attr.Arguments.Count > 1 ? attr.Arguments[1] : null;
                                break;
                            }
                            case "$VKCHAINABLE":
                            {
                                isChainable = true;
                                break;
                            }
                            case "$VKEXTENDSCHAIN":
                            {
                                chainExtensions = attr.Arguments.Count > 1 ? attr.Arguments.Skip(1).ToArray() : null;
                                break;
                            }
                            case "$VKCHAINSTART":
                            {
                                chainExtenderss = attr.Arguments.Count > 1 ? attr.Arguments.Skip(1).ToArray() : null;
                                break;
                            }
                            case "$VKALIASOF":
                            {
                                aliasOf = attr.Arguments.Count > 1 ? attr.Arguments[1] : null;
                                break;
                            }
                            case "$VKALIASES":
                            {
                                aliases = attr.Arguments.Count > 1 ? attr.Arguments.Skip(1).ToArray() : null;
                                break;
                            }
                            default:
                            {
                                Console.WriteLine
                                (
                                    $"Unexpected build intrinsic attribute '{attr.Arguments[0]}' on '{@struct.Name}' struct!"
                                );
                                break;
                            }
```

2021-12-01 19:38 UTC, Perksey commented on src/Core/Silk.NET.BuildTools/Bind/StructWriter.cs
> +                Array.Empty<string>()
```suggestion
                Enumerable.Empty<string>()
```

2021-12-01 19:38 UTC, Perksey commented on src/Core/Silk.NET.BuildTools/Bind/StructWriter.cs
> +                        (structField, ref bitfieldIdx, ref bitfieldPsz, ref bitfieldRbs, ref bitfieldLbt, sw, profile);
```suggestion
                    WriteBitfield
                    (
                        structField, ref bitfieldIdx, ref bitfieldPsz, ref bitfieldRbs, ref bitfieldLbt, sw, profile
                    );
```

2021-12-01 19:38 UTC, Perksey commented on src/Lab/Experiments/PrototypeStructChaining/.gitignore
> +## Ignore Visual Studio temporary files, build results, and
This can probably be removed as it's covered by the root gitignore.

2021-12-01 19:38 UTC, Perksey commented on src/Lab/Experiments/PrototypeStructChaining/.idea/.idea.PrototypeStructChaining/.idea/.gitignore
> +# Default ignored files
Can you delete the .idea files please

2021-12-01 19:38 UTC, Perksey commented on src/Vulkan/Silk.NET.Vulkan.Test/Silk.NET.Vulkan.Test.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Can we name this project `.Tests` instead of `.Test`

2021-12-01 19:45 UTC, Perksey commented
Also can you please do a full BuildTools run before continuing (this may pull in unrelated changes, but that's fine as I'll know not to look in the folders that aren't Vulkan or OpenXR) primarily so I can grasp the implications of this on OpenXR.

Finally feel free to add a blog post in website/blog:
- here's an example commit showing how to add a blog post to the website: https://github.com/dotnet/Silk.NET/pull/612/commits/b6fc25d190ffe9a235bd0e07352ad51f8fa4988f
- for the preview image I recommend using this one: https://github.com/dotnet/brand/blob/main/dotnet-bot-illustrations/Scenes/dotnet-bot_scene_limo-driver.png

Thanks.

2021-12-01 20:27 UTC, thargy commented
> Also can you please do a full BuildTools run before continuing (this may pull in unrelated changes, but that's fine as I'll know not to look in the folders that aren't Vulkan or OpenXR) primarily so I can grasp the implications of this on OpenXR.

As I mentioned in the Working Group, I'm not confident doing this and I still have quite a few projects not building on my dev machine due to dependencies.  I also have to have quite a lot of projects unloaded for the solution to be workable.  @HurricanKai suggested he'd be happy to do a `BuildTools` run for me, and I'm happy to look at and address any issues that arise.

> Finally feel free to add a blog post in website/blog:

I plan on finishing the documentation and PR today/tomorrow to give it a chance of making the next release.  Once it gets merged I'll happily write a blog post.  Hopefully, you will find the documentation pretty extensive.

2021-12-01 20:30 UTC, Perksey commented
Ah no worries, I'll run BuildTools full now.

2021-12-03 06:11 UTC, HurricanKai approved these changes
It's very difficult to review this, due to GitHub almost crashing, but I've looked at the Chaining implementation and it lgtm.
@Perksey I think the BuildTools stuff looks good as well, but that's your expertise

2021-12-03 11:31 UTC, Perksey approved these changes

2021-12-03 11:31 UTC, merged