Regenerate bindings & post patch notes for 2.16
dotnet/Silk.NET pull request #983
Opened 2022-07-31 22:24 UTC by Perksey

Coming in to support this update seeing as it's long overdue and much needed!

Draft until CI is fixed.

2022-07-31 22:29 UTC, Beyley requested changes

2022-07-31 22:29 UTC, Beyley commented on build/props/common.props
> +            This update may result in your projects have a lot of deprecation warnings. We believe this update contains much-needed improvements to both Silk.NET and code consuming it, but we appecia
`This update may result in your projects have a lot of deprecation warnings.` should be changed to `This update may result in your projects having a lot of deprecation warnings.`

2022-08-01 16:10 UTC, Perksey commented
CI... passed?

2022-08-01 23:29 UTC, Perksey commented
Forgot to say this is ready for review.

2022-08-02 03:16 UTC, merged