Optimize Scalar.As
dotnet/Silk.NET pull request #988
Opened 2022-08-03 22:36 UTC by Perksey

2022-08-04 07:22 UTC, Beyley approved these changes
looks good to me, although that isn't legal advice i'm not a doctor i think at least

2022-08-04 08:42 UTC, HurricanKai requested changes
I'll check the disasm and merge. I'm assuming this is good, but blocking merge until we can be sure.

2022-08-04 08:45 UTC, HurricanKai approved these changes
Only checked discord now and saw you've already done everything 😅

2023-01-15 20:13 UTC, Perksey commented
I'm hoping one day this will light up, but failing that I need to add a "mono path" that stops mono from producing invalid assembly (basically just having a file with the old, unoptimized code in it. I think our blazor activity gives us reasonable evidence that it does try to specialize these generics even with the code unoptimized for CoreCLR so we may be good to do so anyway. sucks, but that's mono for you)

2023-01-22 15:06 UTC, merged